# Basic
name:               "Swarm Lab"
title:              "Swarm Lab at UT Austin"
description:        "This is the official website of the Swarm Lab at UT Austin."


# URL
url:                https://utaustin-swarmlab.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "HOME"
    href:           "/"
  - name:           "ABOUT"
    href:           "/about"
  - name:           "PUBLICATIONS"
    href:           "/publications"
  - name:           "PEOPLE"
    href:           "/people"
  - name:           "LAB PICTURES"
    href:           "/lab_pictures"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  -
    scope:
      path:         ""
      type:         "lab_pictures"
    values:
      layout:       "albums"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
  lab_pictures:
    output: true
    permalink: /lab_pictures/:title/index.html

scholar:
  style: chicago-author-date # apa, chicago-author-date, ieee, , nature, vancouver
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"